language: go
go:
  - 1.7
os:
  - linux
  - osx
env:
  - USE_RUBY=2.2.10
  - USE_RUBY=2.3.7
  - USE_RUBY=2.4.4
  - USE_RUBY=2.5.1

before_install:
  - rvm use $USE_RUBY --install --fuzzy
script:
  - RAILS_ENV="" make
